setting:
  binWidth: 1
  label: 1
  interpolator: 'sitkBSpline' 
  resampledPixelSpacing: [3, 3, 3] 
  normalize: TRUE
  normalizeScale: 100
  voxelArrayShift: 300
  
imageType:
  Original: {} 
  Wavelet: {} 
  LoG: {sigma: [2.0, 3.0, 4.0, 5.0, 6.0]}
  Square: {} 
  SquareRoot: {} 
  Logarithm: {} 
  Exponential: {} 
  Gradient: {} 

featureClass:
  shape:
  firstorder: 
  glcm:  
  glrlm: 
  glszm:
  ngtdm:
  gldm:
